### ISSUE TITLE
Possible Memleak

### ISSUE THREAD

**Issue by cdgraff** [CoinFuMasterShifu/janusminer#4]
![image](https://github.com/CoinFuMasterShifu/janusminer/assets/1087447/e8d261ee-df27-4b92-9961-b487592309cb)

`[Fri Dec 22 03:22:08 2023] Out of memory: Killed process 128001 (wart-miner) total-vm:143693604kB, anon-rss:126727712kB, file-rss:141504kB, shmem-rss:4224kB, UID:1000 pgtables:252888kB oom_score_adj:0`

**Comment by CoinFuMasterShifu** [comment]
There is no memleak (I am not touching `new` or `delete`) but high mem usage, I will try to improve things in  a future release.

**Comment by CoinFuMasterShifu** [comment]
Mem usage is determined by total GPU hashrate.
