### ISSUE TITLE
The Miner crashes after a few rounds when running two gpus

### ISSUE THREAD

**Issue by thekillsquad007** [CoinFuMasterShifu/janusminer#8]
My hardware - CPU- ryzen 9 5900x, Ram - 32 GB, OS- MMPOS, GPU - AMD 7800xt, 5600xt, Driver version - ROCM 6.0

<img width="472" alt="janusminer" src="https://github.com/CoinFuMasterShifu/janusminer/assets/44879237/8706eb71-5837-4062-b5e0-9263b5ec9905">

This happens within a minute or two. Anyway to fix this issue?

**Comment by CoinFuMasterShifu** [comment]
Did you observe how the RAM usage was?

**Comment by thekillsquad007** [comment]
No, i haven't but i found a temporary fix and it works even though its a bit silly. Running the cards in different instances solved it somehow and didn't Crash under a minute.

**Comment by CoinFuMasterShifu** [comment]
Yes this miner is just for now, eventually there will be professional miners and pools soon!
